const CORE_VERSION="0.12.6";
const CORE_DEFAULT=`https://cdn.jsdelivr.net/npm/@ffmpeg/core@${CORE_VERSION}/dist/umd/ffmpeg-core.js`;
const TYPES={LOAD:"LOAD",EXEC:"EXEC",WRITE_FILE:"WRITE_FILE",READ_FILE:"READ_FILE",DELETE_FILE:"DELETE_FILE",RENAME:"RENAME",CREATE_DIR:"CREATE_DIR",LIST_DIR:"LIST_DIR",DELETE_DIR:"DELETE_DIR",ERROR:"ERROR",DOWNLOAD:"DOWNLOAD",PROGRESS:"PROGRESS",LOG:"LOG",MOUNT:"MOUNT",UNMOUNT:"UNMOUNT"};
const ERROR_UNKNOWN_MESSAGE_TYPE=new Error("unknown message type"),ERROR_NOT_LOADED=new Error("ffmpeg is not loaded, call `await ffmpeg.load()` first"),ERROR_IMPORT_FAILURE=new Error("failed to import ffmpeg-core.js");
let ffmpeg;
async function loadCore({coreURL=CORE_DEFAULT,wasmURL,workerURL}={}){const first=!ffmpeg,finalWasmURL=wasmURL||coreURL.replace(/\.js$/g,".wasm"),finalWorkerURL=workerURL||coreURL.replace(/\.js$/g,".worker.js");try{importScripts(coreURL)}catch(_){self.createFFmpegCore=(await import(coreURL)).default;if(!self.createFFmpegCore)throw ERROR_IMPORT_FAILURE}ffmpeg=await self.createFFmpegCore({mainScriptUrlOrBlob:`${coreURL}#${btoa(JSON.stringify({wasmURL:finalWasmURL,workerURL:finalWorkerURL}))}`});ffmpeg.setLogger(data=>self.postMessage({type:TYPES.LOG,data}));ffmpeg.setProgress(data=>self.postMessage({type:TYPES.PROGRESS,data}));return first}
function exec({args,timeout=-1}){ffmpeg.setTimeout(timeout);ffmpeg.exec(...args);const ret=ffmpeg.ret;ffmpeg.reset();return ret}
function writeFile({path,data}){ffmpeg.FS.writeFile(path,data);return true}function readFile({path,encoding}){return ffmpeg.FS.readFile(path,{encoding})}function deleteFile({path}){ffmpeg.FS.unlink(path);return true}function rename({oldPath,newPath}){ffmpeg.FS.rename(oldPath,newPath);return true}function createDir({path}){ffmpeg.FS.mkdir(path);return true}function listDir({path}){const names=ffmpeg.FS.readdir(path),nodes=[];for(const name of names){const stat=ffmpeg.FS.stat(`${path}/${name}`);nodes.push({name,isDir:ffmpeg.FS.isDir(stat.mode)})}return nodes}function deleteDir({path}){ffmpeg.FS.rmdir(path);return true}function mount({fsType,options,mountPoint}){const fs=ffmpeg.FS.filesystems[fsType];if(!fs)return false;ffmpeg.FS.mount(fs,options,mountPoint);return true}function unmount({mountPoint}){ffmpeg.FS.unmount(mountPoint);return true}
self.onmessage=async({data:{id,type,data}})=>{const trans=[];let result;try{if(type!==TYPES.LOAD&&!ffmpeg)throw ERROR_NOT_LOADED;switch(type){case TYPES.LOAD:result=await loadCore(data);break;case TYPES.EXEC:result=exec(data);break;case TYPES.WRITE_FILE:result=writeFile(data);break;case TYPES.READ_FILE:result=readFile(data);break;case TYPES.DELETE_FILE:result=deleteFile(data);break;case TYPES.RENAME:result=rename(data);break;case TYPES.CREATE_DIR:result=createDir(data);break;case TYPES.LIST_DIR:result=listDir(data);break;case TYPES.DELETE_DIR:result=deleteDir(data);break;case TYPES.MOUNT:result=mount(data);break;case TYPES.UNMOUNT:result=unmount(data);break;default:throw ERROR_UNKNOWN_MESSAGE_TYPE}}catch(e){self.postMessage({id,type:TYPES.ERROR,data:e?.toString?.()||String(e)});return}if(result instanceof Uint8Array)trans.push(result.buffer);self.postMessage({id,type,data:result},trans)};
